### ISSUE TITLE
Add support for Pinscape AIO

### ISSUE THREAD

**Issue by MikePinball** [mjrgh/PinscapeConfigTool#11]
I made a first attempt to add support for the Pinscape AIO to the config tool. It is similar to the expansion boards but includes an extra chime board. Rather than adding a new config parameter, I added a new value (2) for the hardware type parameter. See the attached file and bitmap icon. 

Much of code is common between hardware types 1 and 2 so there are places where tests like "== 1" are changed to "!= 0". And some unique code is added for hardware type 2. 

One change I haven't done yet is that the location and pin descriptions should also be changed to be "Pinscape AIO" and the corresponding pin number. I left this for now because it depends on how you want to proceed with the proposed change.
[PinscapeAIO_html_changes.zip](https://github.com/mjrgh/PinscapeConfigTool/files/4001395/PinscapeAIO_html_changes.zip)

**Comment by mjrgh** [comment]
The best way to send changes is pull requests on github, at least for the config tool. mbed has their own repos setup and I’m not sure if they have an equivalent.

You might want to hold off until I check in some changes I have out, to minimize merging work.

For the “type == 1” sorts of tests, I don’t think you want to make those  “!= 0” tests, since that assumes there’ll never be a type 3 or 4 or...  Better to make them explicitly cover the cases they should cover, and only those cases.

Mike



On Dec 25, 2019, at 8:42 PM, MikePinball <notifications@github.com> wrote:

﻿

I made a first attempt to add support for the Pinscape AIO to the config tool. It is similar to the expansion boards but includes an extra chime board. Rather than adding a new config parameter, I added a new value (2) for the hardware type parameter. See the attached file and bitmap icon.

Much of code is common between hardware types 1 and 2 so there are places where tests like "== 1" are changed to "!= 0". And some unique code is added for hardware type 2.

One change I haven't done yet is that the location and pin descriptions should also be changed to be "Pinscape AIO" and the corresponding pin number. I left this for now because it depends on how you want to proceed with the proposed change.
PinscapeAIO_html_changes.zip<https://github.com/mjrgh/PinscapeConfigTool/files/4001395/PinscapeAIO_html_changes.zip>

**Comment by MikePinball** [comment]
Ok I will hold off for now. I am happy to create a pull request with the integrated changes. I just wanted to give you a heads up and have design discussion before making too many changes. I am guessing that you are ok with a new hardware type (2) rather than a new flag?

I can change the code but there is going to be a number of places that will now say "==1 or ==2" instead of "==1"

Also I would like your advice on the board counts. I really want expansionBoards.ext1 and expansionBoards.ext2 to be zero but under the covers, all 73 ports on the Pinscape AIO are listed just like the 33 ports on the Pinscape main board. I am thinking that I might have to duplicate a lot of the data you already setup in variables like expOutPortAlias, expansionBoardFactoryConfig, and expansionBoardFactoryXConfig as well as some of the supporting code. This is potentially going to lead to issues of code maintenance unless we can find a good way to separate out the similar and different parts between Pinscape Expansion boards and Pinscape AIO.

Another alternative is to "hack" the board counts so they have -1 or +1 added to them in the right places for Pinscape AIO. Then I can also use a loop to change location and pin descriptions for the 73 ports of the Pinscape AIO.

**Comment by MikePinball** [comment]
This issue can be closed as is replaced by a pull request.
