### ISSUE TITLE
Pinscape Controller versus Pinscape Expansion Boards

### ISSUE THREAD

**Issue by MikePinball** [mjrgh/PinscapeConfigTool#3]
The Pinscape Expansion boards are one instantiation/configuration of the Pinscape Controller but to almost everyone they are the same thing. But in fact they are different and there could be other instantiations supported by the configuration tool such as all outputs on 74HC595 except for 16 LED constant current outputs for lamps etc.

The custom interface to add outputs is not consistent. For example the following two sequences result in outputs with two different orders:
1. Add 1 595, add 1 TLC5940, add second 595
2. Add 2 595, add 1 TLC5940

The output pins are assigned in the order that the user adds them in the user interface. Instead some kind of priority scheme is needed so that TLC5940 or 595 outputs are always first in the list.

The same is probably true for the TLC59116.

**Comment by MikePinball** [comment]
I like the fact that the (custom) port ordering is stored as part of the configuration so perhaps this rule only needs to be enforced in one session of the config tool. If you want to add ports later then either they are added at the end (like today) and the port numbering is maintained or the user has to know to delete interfaces and then readd them to get the ordering they want.

**Comment by mjrgh** [comment]
I don't understand why this would be desirable.  The output port ordering is for the PC-side software's sake (DOF, LedWiz clients), and is otherwise arbitrary.  PC clients don't care whether or not the TLC5940 ports are grouped together; they have no idea what a TLC5940 port even is.  In some cases it's even desirable *not* to group ports by external chip association.  If you look at the defaults for the expansion boards, the ports are deliberately not grouped to make the TLC5940 connections contiguous, because the thing that some PC-side software cares about is which ports are within the magic range 1-32 (the ports visible to legacy LedWiz clients).  If you have some other reason you want to group TLC5940 ports together for a particular installation, and you want to add them after the fact, you can just move them around manually in the list to get the order you prefer, right?

**Comment by MikePinball** [comment]
Closed as not needed.
