### ISSUE TITLE
Question: ZB Launch Ball - Intended Bahaviour...???

### ISSUE THREAD

**Issue by Zappo-II** [mjrgh/PinscapeConfigTool#33]
### This is what I have:

- I have my Pinscape configured to Send Enter when the Plunger is pressed...
- I have configured a DOF Input to ZB Launch Ball...
- I have Updated PinscapeFirmware and PinscapeConfigTool to the new versions yesterday...
- The situation described below was like this before and is like this after the update...
- I have VPX 10.7.3 final
- I have the DOF Version from your WebSite
- I have B2S Server 2.1.1.
- Everything else works like I would expect it

### This is what I do:

When Using **"Terminator 2 - Judgement Day"** I can

- Lauch the ball by bumping the Plunger...
- Fire the Cannon, when loaded, by bumping the Plunger...

I think that this is exactly the intended behaviour...

```
  Sub table1_KeyDown(ByVal keycode)
  	If keycode = PlungerKey  Then Controller.Switch(34)=1
   	If vpmKeyDown(keycode) Then Exit Sub
  End Sub
   
   Sub table1_KeyUp(ByVal keycode)
  	If keycode = PlungerKey  Then Controller.Switch(34)=0
   	If vpmKeyUp(keycode) Then Exit Sub
  End Sub
```

### This is what I am wondering about:

If I use the **"ST-TNG"** Table
- I can Launch the ball by bumping the Plunger...
- But if the "Cannon" is loaded, I can hit as much and as often as I want on the Plunger, it won't fire...

```
Sub table1_KeyDown(ByVal Keycode)
    If KeyCode = MechanicalTilt Then
        vpmTimer.PulseSw vpmNudge.TiltSwitch
        Exit Sub
    End if
    If keycode = PlungerKey Then Controller.Switch(12) = 1
    If keycode = keyFront Then Controller.Switch(11) = 1
    If vpmKeyDown(keycode) Then Exit Sub
End Sub

Sub table1_KeyUp(ByVal Keycode)
    If keycode = PlungerKey Then Controller.Switch(12) = 0
    If keycode = keyFront Then Controller.Switch(11) = 0
    If vpmKeyUp(keycode) Then Exit Sub
End Sub
```

If I use the **"The Getaway - High Speed 2"** Table
- I can Launch the ball by bumping the Plunger...
- When the Table says "Shift Gears", I can hit as much and as often as I want on the Plunger, it won't fire...

```
Sub Table1_KeyDown(ByVal KeyCode)
	If KeyDownHandler(keycode) Then Exit Sub
	If keycode = PlungerKey Then Controller.Switch(34) = True
	if KeyCode = LeftTiltKey Then Nudge 90, 4
	if KeyCode = RightTiltKey Then Nudge 270, 4
	if KeyCode = CenterTiltKey Then Nudge 0, 12
	If keycode = LeftMagnaSave Then:Controller.Switch(33) = 1:End If
	If KeyCode = LeftFlipperKey then FastFlips.FlipL True :  FastFlips.FlipUL True
	If KeyCode = RightFlipperKey then FastFlips.FlipR True :  FastFlips.FlipUR True
'(Do not use Exit Sub, this script does not handle switch handling at all!)
End Sub

Sub Table1_KeyUp(ByVal KeyCode)
	If KeyUpHandler(keycode) Then Exit Sub
	If keycode = PlungerKey Then Controller.Switch(34) = False
	If keycode = LeftMagnaSave Then:Controller.Switch(33) = False:End If
	If KeyCode = LeftFlipperKey then FastFlips.FlipL False :  FastFlips.FlipUL False
	If KeyCode = RightFlipperKey then FastFlips.FlipR False :  FastFlips.FlipUR False
End Sub
```

(_the code given is native Table code, so please don't yell at me for crappyness using true/false and block vs inline if and stuff_)

Both Tables (there are some more Tables that also behave like these) have Key Events that "use the PlungerKey" and if I hit the Enter key on my Keyboard, the intended keyevent condition is executed...

I would expect that hitting / bumping / using / whatevering the plunger should lead to the same "result", shouldn't it...???

I can see no obvious reason for this, even looking into the specific keyEvent implementations of the before mentioned tables gives me any explanation or insights why (Have no Idea what KeyUp/DownHandler of TheGetaway does, seems to be something global not defined inside the table script)...

All mentioned tables are listed by dof config tool as supporting ZB Launch Ball "Toy"...

Am I using or understanding this in a wrong way...???

Please Clarify...

**Comment by mjrgh** [comment]
You should look at the DOF Config Tool settings for the table - 90% odds that's where the problem is.  The DOF configs for a lot of tables with Launch Ball buttons think it would be clever to enable ZB Launch conditionally on the plunger chute switch. So they miss the other places you might need to use it, like the T2 or STTNG cannons.  There's generally no reason for ZB Launch to be set to anything other than ON for tables with launch buttons - if you change it in to ON in those games, then the plunger should start working throughout the game.

**Comment by Zappo-II** [comment]
Ok, THX for pointing that out...
I checked and indeed it is exactly like that...

DOF - Config states:
- T2JD - Has `ZB Lauch Ball` set to `ON`
- STTNG - Conditionally
- TGHS2 - Conditionally
- SW-Tril - Conditionally

What purpose does it serve to have ZB Launch Ball on conditionally...??? - None from your point of view (and I'd like to subscribe to that), but why would a Table Author / DOF Config Editor think of that...???

Is there a way to somehow _override_ the table specific DOF config setting...??? I imagine that each and every PinScape User with Plunger Assembly installed would feel the same about that, won't they...???

It seems very tedious to me to fix this for each and every table in the specific DOF config...
I could imagine that having a Config Switch inside the PinScape(Firmware and Config Tool) to flip it to either "Listen to DOF Port" (conditional) or "Always On" (unconditional) would be really great, wouldn't it...???

**Comment by mjrgh** [comment]
> What purpose does it serve to have ZB Launch Ball on conditionally...???

None; it's an error in the DOF Config Tool database.  From talking to Arngrim (the creator of the tool) about this years ago, I gather that all of the ZB Launch entries were added mechanically by copying the existing Launch Ball Button Light entries, where there is some logic to making them contextual.  But I think everyone agrees that was a well-intentioned mistake.  The semantics of ZB Launch are rather different.  ZB Launch's formal meaning is "the currently loaded table has a Launch Ball button in place of a plunger".  I don't think anyone imagines that the original Star Trek: The Next Generation machines fluctuated between having a Launch Ball button and a traditional plunger at different points during play.  The reason that T2 works is that I reported this to Arngrim years ago specifically for T2.  But I don't think he ever proactively went through the database and fixed the many other games with the same problem, so similar reports will probably be needed on a game-by-game basis.

> Is there a way to somehow override the table specific DOF config setting...???

Sure, the DOF Config Tool lets you do that.

> It seems very tedious to me to fix this for each and every table in the specific DOF config...

I agree, it ought to be fixed in the database so that everyone gets the correct settings by default.  It hasn't been a priority for the maintainers to go out and fix all of the existing entries proactively, clearly, since all of these erroneous entries have been in there for years, but you can help by clicking the "Submit for Public Consideration" button for each table you fix.

> I could imagine that having a Config Switch inside the PinScape(Firmware and Config Tool) to flip it to either "Listen to DOF Port" (conditional) or "Always On" (unconditional) would be really great, wouldn't it...???

So you're picturing firing up the Config Tool every time you want to play ST:TNG, going in and changing settings, saving and rebooting, playing ST:TNG, firing up the Config Tool again, changing the settings back, saving and rebooting?  This seems less tedious than fixing the DOF entry, once?

**Comment by Zappo-II** [comment]
Thank you for getting into this in that depth and pointing out the given and intended functionality in addition to explaining to me where I was taking a wrong turn in stupidly asking for a functional change...

I obviously was mistaken by thinking that the ZB Launch and the genuine plunger functionality are NOT exclusive...

I thought that the plunger would work genererally via analog joystick signal and that only if pushed toward the "dead" zone (towards the cab) it would additionally send an Enter Key Press. Thinking of that in that way somehow made sense for me...

Anyways, I'll go for fixing the Entries in DOF Config and proposing them for public consideration...

Please let me again express my thankfulness for your Pinscape and Virtual CAB community work and for the amount of professionality and in depth knowledge you expose, each and every time... that is not very common when it comes to people doing this kind of suff on a "as a hobby" basis...

THX and Cheers...
