### ISSUE TITLE
Add other output interfaces

### ISSUE THREAD

**Issue by MikePinball** [mjrgh/PinscapeConfigTool#4]
KL25Z output ports that are not assigned for other purposes should probably have an output driver (such as the ULN2803A).

This can be enforced by having a way to explicitly add ports using the ULN2803A much like the 74HC595. That is start with no output ports and let the user add ports by explicitly 
1. Using interfaces such as ULN2803A, TLC5940 etc
2. Using virtual ports
3. Using individual output pins (should be discouraged).

Also other drivers should be added such as the ULN2064 (as used for the medium LED outputs).

**Comment by mjrgh** [comment]
If you want to refile this as "Add a ULN2083A chip type", I'd be okay with that, but the current behavior is preferable to the notion that every pin has to be assigned to some particular external chip.  That would be confusing to people who want to attach a novel device.  Consider:

"I want to hook port PTXY up to my Arduino/Sainsmart/random eBay relay board/random eBay MOSFET board/custom controller board, but I don't see that in the list.  What do I do?"

"Oh, you just pretend that it's a ULN2083A, because ULN2083A really means 'other external connection'."

**Comment by MikePinball** [comment]
I think you misunderstood this a little. I will write 2 new requirements to explain what I am asking.
