### ISSUE TITLE
Change behavor of used ports

### ISSUE THREAD

**Issue by MikePinball** [mjrgh/PinscapeConfigTool#5]
I/O ports are reserved for use for the TLC5940, ULN6064 etc interfaces. When the count is non-zero these ports are shown with a red "no-entry" sign. That is good but they are not implicitly removed from the output numbering - the user has to be do this manually.

Because there is no choice here the ports have to be excluded. But the numbering is left in place which is confusing.

First these ports should be given a new type (similar to virtual but called "Reserved").  By default the ports should be automatically removed (or put back) when an output interface (e.g. TLC5940) is chosen. Yes this changes the numbering but most of the time required for a new design. Users can always put back the "missing" ports or insert some "null" or virtual ports to get the numbering correct.

**Comment by mjrgh** [comment]
I don't think this is the way to go.  The current behavior is intentional.  As a user, I don't want changes in one part of the UI to make implicit changes in other parts, particularly ones that might be out of the current view.  Assigning a port to a new use intentionally doesn't remove an existing assignment for the port, but rather flags each use as having a conflict that needs to be resolved (the red circle-slash symbol).  This lets the user determine what to do about the conflict, and importantly preserves information about the prior assignment so that the user can see the implication of the change and back it out if needed.
